"""initial schema: core entities

Revision ID: 741ad0dc7423
Revises: 
Create Date: 2026-08-23 09:23:38.125445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '741ad0dc7423'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('razorpay_merchant_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_table('policies',
    sa.Column('cause', sa.String(length=100), nullable=False),
    sa.Column('allowed_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('requires_consent', sa.Boolean(), nullable=False),
    sa.Column('blocks_on_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('cause', name=op.f('uq_policies_cause'))
    )
    op.create_table('customers',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('consent_status', sa.String(length=50), nullable=False),
    sa.Column('customer_segment', sa.String(length=100), nullable=True),
    sa.Column('customer_lifetime_value', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_customers_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('invoices',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('days_overdue', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoices_customer_id_customers')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_invoices_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_table('payment_events',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulation_status', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('decline_code', sa.String(length=100), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_payment_events_customer_id_customers')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_payment_events_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_payment_events_event_id')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payment_events_idempotency_key'))
    )
    op.create_table('subscriptions',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_subscriptions_customer_id_customers')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_subscriptions_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_table('recovery_cases',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('payment_event_id', sa.UUID(), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_recovery_cases_customer_id_customers')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_recovery_cases_merchant_id_merchants')),
    sa.ForeignKeyConstraint(['payment_event_id'], ['payment_events.id'], name=op.f('fk_recovery_cases_payment_event_id_payment_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_cases')),
    sa.UniqueConstraint('payment_event_id', name=op.f('uq_recovery_cases_payment_event_id'))
    )
    op.create_table('audit_logs',
    sa.Column('recovery_case_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('input_reference', sa.String(length=255), nullable=True),
    sa.Column('output_reference', sa.String(length=255), nullable=True),
    sa.Column('simulation_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_audit_logs_recovery_case_id_recovery_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('decisions',
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('proposed_action', sa.String(length=50), nullable=False),
    sa.Column('policy_decision', sa.String(length=50), nullable=False),
    sa.Column('policy_reason', sa.Text(), nullable=True),
    sa.Column('policy_rule_triggered', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_decisions_recovery_case_id_recovery_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_table('diagnoses',
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('cause', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_llm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_diagnoses_recovery_case_id_recovery_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnoses'))
    )
    op.create_table('model_predictions',
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('recovery_probability', sa.Float(), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_model_predictions_recovery_case_id_recovery_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_predictions'))
    )
    op.create_table('actions',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_actions_decision_id_decisions')),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_actions_recovery_case_id_recovery_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    op.create_table('outcomes',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_outcomes_action_id_actions')),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_outcomes_recovery_case_id_recovery_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes')),
    sa.UniqueConstraint('action_id', name=op.f('uq_outcomes_action_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    op.drop_table('actions')
    op.drop_table('model_predictions')
    op.drop_table('diagnoses')
    op.drop_table('decisions')
    op.drop_table('audit_logs')
    op.drop_table('recovery_cases')
    op.drop_table('subscriptions')
    op.drop_table('payment_events')
    op.drop_table('invoices')
    op.drop_table('customers')
    op.drop_table('policies')
    op.drop_table('merchants')
    # ### end Alembic commands ###
